const ResponseTypes = {
    FIELD_ERRORS: 'FIELD_ERRORS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USING_GOOGLE_SERVICE: "USING_GOOGLE_SERVICE",
    WAITING_VERIFY_EMAIL: "WAITING _VERIFY_EMAIL",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    USER_WITH_EMAIL_NOTFOUND: "USER_WITH_EMAIL_NOTFOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS"
};
  
module.exports = ResponseTypes;