const ResponseTypes = {
    FIELD_ERRORS: 'FIELD_ERRORS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USING_GOOGLE_SERVICE: "USING_GOOGLE_SERVICE",
    WAITING_VERIFY_EMAIL: "WAITING _VERIFY_EMAIL",
    INTERNAL_ERROR: "INTERNAL_ERROR"
};
  
module.exports = ResponseTypes;